version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: database
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - ./server/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 4000:4000
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
